<?php

declare(strict_types=1);

namespace GatoGraphQL\GatoGraphQL;

class Environment
{
    public const ADD_EXCERPT_AS_DESCRIPTION = 'ADD_EXCERPT_AS_DESCRIPTION';
    public const GROUP_FIELDS_UNDER_TYPE_FOR_PRINT = 'GROUP_FIELDS_UNDER_TYPE_FOR_PRINT';
    public const NO_ITEMS_SELECTED_LABEL = 'NO_ITEMS_SELECTED_LABEL';
    public const SETTINGS_VALUE_LABEL = 'SETTINGS_VALUE_LABEL';
    public const EDITING_ACCESS_SCHEME = 'EDITING_ACCESS_SCHEME';
    public const ENABLE_SETTING_CLIENT_IP_ADDRESS_SERVER_PROPERTY_NAME = 'ENABLE_SETTING_CLIENT_IP_ADDRESS_SERVER_PROPERTY_NAME';
    public const GATOGRAPHQL_WEBSITE_URL = 'GATOGRAPHQL_WEBSITE_URL';
    public const GATOGRAPHQL_REQUEST_EXTENSION_PAGE_URL = 'GATOGRAPHQL_REQUEST_EXTENSION_PAGE_URL';
    public const GATOGRAPHQL_BUNDLES_PAGE_URL = 'GATOGRAPHQL_BUNDLES_PAGE_URL';
    public const GATOGRAPHQL_EXTENSIONS_PAGE_URL = 'GATOGRAPHQL_EXTENSIONS_PAGE_URL';
    public const GATOGRAPHQL_EXTENSIONS_REFERENCE_PAGE_URL = 'GATOGRAPHQL_EXTENSIONS_REFERENCE_PAGE_URL';
    public const MARKETPLACE_PROVIDER_PLUGIN_UPDATES_SERVER_URL = 'MARKETPLACE_PROVIDER_PLUGIN_UPDATES_SERVER_URL';
    public const USE_SCHEMA_CONFIGURATION_IN_INTERNAL_GRAPHQL_SERVER = 'USE_SCHEMA_CONFIGURATION_IN_INTERNAL_GRAPHQL_SERVER';
    public const ENABLE_SCHEMA_TUTORIAL_PAGE = 'ENABLE_SCHEMA_TUTORIAL_PAGE';
    public const INSTALL_PLUGIN_SETUP_DATA = 'INSTALL_PLUGIN_SETUP_DATA';
    public const SHOW_BUNDLES_CONTAINING_REFERENCED_EXTENSIONS_ON_TUTORIAL = 'SHOW_BUNDLES_CONTAINING_REFERENCED_EXTENSIONS_ON_TUTORIAL';
    public const IS_SCHEMA_CONFIGURATION_ENABLED_BY_DEFAULT = 'IS_SCHEMA_CONFIGURATION_ENABLED_BY_DEFAULT';
    public const DISPLAY_ENABLE_LOGS_SETTINGS_OPTION = 'DISPLAY_ENABLE_LOGS_SETTINGS_OPTION';
    public const ENABLE_LOG_COUNT_BADGES = 'ENABLE_LOG_COUNT_BADGES';
    public const ENABLE_LOG_COUNT_BADGES_BY_SEVERITY = 'ENABLE_LOG_COUNT_BADGES_BY_SEVERITY';
}
