<?php

declare(strict_types=1);

namespace GatoGraphQL\GatoGraphQL;

class Environment
{
    public const MODULE_URL_BASE = 'MODULE_URL_BASE';
    public const ADD_EXCERPT_AS_DESCRIPTION = 'ADD_EXCERPT_AS_DESCRIPTION';
    public const GROUP_FIELDS_UNDER_TYPE_FOR_PRINT = 'GROUP_FIELDS_UNDER_TYPE_FOR_PRINT';
    public const NO_ITEMS_SELECTED_LABEL = 'NO_ITEMS_SELECTED_LABEL';
    public const SETTINGS_VALUE_LABEL = 'SETTINGS_VALUE_LABEL';
    public const ENDPOINT_SLUG_BASE = 'ENDPOINT_SLUG_BASE';
    public const PERSISTED_QUERY_SLUG_BASE = 'PERSISTED_QUERY_SLUG_BASE';
    public const EDITING_ACCESS_SCHEME = 'EDITING_ACCESS_SCHEME';
    public const ENABLE_SETTING_CLIENT_IP_ADDRESS_SERVER_PROPERTY_NAME = 'ENABLE_SETTING_CLIENT_IP_ADDRESS_SERVER_PROPERTY_NAME';
    public const GATO_GRAPHQL_WEBSITE_URL = 'GATO_GRAPHQL_WEBSITE_URL';
    public const GATO_GRAPHQL_REQUEST_EXTENSION_PAGE_URL = 'GATO_GRAPHQL_REQUEST_EXTENSION_PAGE_URL';
    public const GATO_GRAPHQL_EXTENSIONS_PAGE_URL = 'GATO_GRAPHQL_EXTENSIONS_PAGE_URL';
    public const USE_SCHEMA_CONFIGURATION_IN_INTERNAL_GRAPHQL_SERVER = 'USE_SCHEMA_CONFIGURATION_IN_INTERNAL_GRAPHQL_SERVER';
}
